apiVersion: apps/v1
kind: Deployment
metadata:
  name: vrd-private
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vrd-private
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: vrd-private
    spec:
      containers:
        - name: vrd-private
          image: bekube/vrd-private:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1  
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
          volumeMounts:
            - name: config
              mountPath: "/etc/nginx/conf.d/default.conf"
              readOnly: true
              subPath: default.conf
      volumes:
        - name: config
          configMap:
            name: vrd-private-configmap
            items:
              - key: default.conf
                path: default.conf 
