apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  

namespace: vrd-skcc

configMapGenerator:
  - name: vrd-private-configmap
    behavior: create
    files:
    - default.conf
