apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base
  

namespace: vrd-skcc

# configMapGenerator:
#   - name: default.config
#     behavior: replace
#     files:
#     - default.conf

patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
# - service.yaml