apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: vrd-skcc

configMapGenerator:
  - name: default.config
    bahavior: replace
    files:
    - default.conf

patchesStrategicMerge:
- path.yaml